"""
E113 (Phase 66) — T_N is TOEPLITZ; pin the exponent a in ||T_N|| ~ N^a/log|t0|.

Structural fact (from the closed form m_{jk}(lam)=e^{-y lam}L_{j-k}^{(-1)}(2y lam), j>=k):
   T[j,k] = -(1/log(t0/2pi)) * A_{j-k},     A_d = sum_n Lambda(n) n^{-(1/2+y+it0)} L_d^{(-1)}(2y log n),
so T_N is a Hermitian Toeplitz matrix generated by {A_d}. Its symbol's exponent has real part exactly
-1/2 for all theta (Re(s/(1-s))=-1/2 on |s|=1), i.e. the symbol is -zeta'/zeta on the CRITICAL LINE:
||T_N|| = truncated-Toeplitz norm of a symbol with poles at the ON-LINE zeros. Growth in N is classical.

Computation is now O(N * #primes) to get {A_d}, then a Toeplitz eigenvalue solve -> fast, large N.
"""
import numpy as np
from scipy.special import eval_genlaguerre
from scipy.linalg import eigvalsh

def prime_powers(X):
    s=np.ones(X+1,bool); s[:2]=False
    for i in range(2,int(X**.5)+1):
        if s[i]: s[i*i::i]=False
    out=[]
    for p in np.nonzero(s)[0]:
        lp=np.log(p); q=p
        while q<=X: out.append((q,lp)); q*=p
    return np.array([(n,l) for n,l in out])

def Ad_all(D, t0, y, ns, lams, Lam):
    # A_d for d=0..D-1 ; L_d^{(-1)}(a) = -a/d L_{d-1}^{(1)}(a) for d>=1, L_0^{(-1)}=1
    a=2*y*lams
    base = Lam/np.sqrt(ns) * np.exp(-y*lams) * np.exp(-1j*t0*lams)   # Lambda n^{-(1/2+y+it0)}
    A=np.empty(D,dtype=complex)
    A[0]=np.sum(base*1.0)
    for d in range(1,D):
        Ld = -(a/d)*eval_genlaguerre(d-1,1,a)
        A[d]=np.sum(base*Ld)
    return A

def TN_from_A(N,A,logt):
    # Hermitian Toeplitz: T[j,k] = -(1/logt) A_{j-k} for j>k ; conj for j<k ; diag = -(2/logt)Re A_0
    idx=np.abs(np.subtract.outer(np.arange(N),np.arange(N)))
    T=-(1.0/logt)*A[idx].astype(complex)
    lower=np.tril(np.ones((N,N),bool),-1)
    T[~lower & ~np.eye(N,dtype=bool)]=np.conj(T.T[~lower & ~np.eye(N,dtype=bool)])
    # rebuild cleanly: lower = -A_d/logt, upper = conj, diag = -2ReA0/logt
    T=np.zeros((N,N),dtype=complex)
    for d in range(N):
        val=-(1.0/logt)*A[d]
        for j in range(d,N):
            T[j,j-d]=val
            if d>0: T[j-d,j]=np.conj(val)
    T[np.diag_indices(N)]=-(2.0/logt)*np.real(A[0])
    return T

if __name__=="__main__":
    y=1.0; pp=prime_powers(20000)   # absolute convergence n^-3/2: 20000 ample
    ns=pp[:,0]; lams=np.log(ns); Lam=pp[:,1]
    print(f"#prime-powers={len(pp)}")

    print("\n(1a) growth in N at t0=1e6 (Toeplitz, closed form):")
    t0=1e6; logt=np.log(t0/(2*np.pi)); Ns=np.array(list(range(4,201,8)))
    A=Ad_all(Ns.max(),t0,y,ns,lams,Lam)
    lmax=np.array([np.max(np.abs(eigvalsh(TN_from_A(N,A,logt)))) for N in Ns])
    for N,l in zip(Ns,lmax):
        if N%16==4 or N==Ns[-1]: print(f"   N={N:4d}  lmax={l:.4f}")
    for lo in [16,80,150]:
        m=Ns>=lo
        a=np.polyfit(np.log(Ns[m]),np.log(lmax[m]),1)[0]
        b=np.polyfit(Ns[m],np.log(lmax[m]),1)[0]
        print(f"   fit N>={lo:3d}: polynomial a={a:.3f} | exponential beta={b:.5f}")

    print("\n(1b) t0-scaling at fixed N=60 (absolute convergence -> all t0 trustworthy):")
    prod=[]
    for t0b in [1e4,1e6,1e8,1e10,1e12,1e15]:
        lg=np.log(t0b/(2*np.pi))
        Ab=Ad_all(60,t0b,y,ns,lams,Lam)
        l=np.max(np.abs(eigvalsh(TN_from_A(60,Ab,lg))))
        prod.append(l*lg)
        print(f"   t0={t0b:.0e}  lmax={l:.4f}  lmax*log={l*lg:.3f}")
    print(f"   product spread {min(prod):.2f}..{max(prod):.2f}  (flat => 1/log whitening holds)")
