#!/usr/bin/env python3
"""generate_lchi5.py: produce N=5000, dps>=80 zero list for L(s, chi_4 mod 5)."""
import os, sys, time, json
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import multiprocessing as mp
import numpy as np
import mpmath as mp_lib
from lchi5_cypari_worker import worker T_MAX = 4400.0
DPS = 80
N_PARTS = 8
N_TARGET = 5000 def main(): parts = [] for i in range(N_PARTS): tmin = T_MAX * i / N_PARTS tmax = T_MAX * (i+1) / N_PARTS parts.append((tmin, tmax, DPS, i)) print(f"[main] launching {N_PARTS} workers for partition of [0, {T_MAX}]", flush=True) print(f"[main] partitions: {[(p[0],p[1]) for p in parts]}", flush=True) ctx = mp.get_context("spawn") t0 = time.time() with ctx.Pool(N_PARTS) as pool: results = [] for res in pool.imap_unordered(worker, parts): idx, tmin, tmax, elapsed, zlist = res print(f"[main] band {idx} [{tmin:.1f},{tmax:.1f}] done in {elapsed:.1f}s, n={len(zlist)}", flush=True) results.append(res) print(f"[main] all workers done in {time.time()-t0:.1f}s", flush=True) results.sort(key=lambda r: r[0]) all_zeros_str = [] for r in results: all_zeros_str.extend(r[4]) print(f"[main] total zeros collected: {len(all_zeros_str)}", flush=True) mp_lib.mp.dps = DPS + 5 # sort & dedup vals = [(mp_lib.mpf(s), s) for s in all_zeros_str] vals.sort(key=lambda x: x[0]) dedup = [] tol = mp_lib.mpf("1e-30") for v, s in vals: if dedup and abs(v - dedup[-1][0]) < tol: continue dedup.append((v, s)) print(f"[main] after dedup: {len(dedup)}", flush=True) if len(dedup) < N_TARGET: print(f"[main] WARNING only {len(dedup)} zeros, less than target {N_TARGET}", flush=True) final = dedup[:N_TARGET] # Validate vs LMFDB lmfdb_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "lmfdb_Lchi5.json") if not os.path.exists(lmfdb_path): lmfdb_path = "/workspace/26aa5002-ae0a-4817-b95d-c1176d5d8281/lmfdb_Lchi5.json" with open(lmfdb_path) as f: txt = f.read() json_start = txt.find("{") data = json.loads(txt[json_start:]) ref = data["positive_zeros"] print(f"[main] LMFDB reference has {len(ref)} zeros", flush=True) nref = min(len(ref), len(final)) max_diff = mp_lib.mpf(0) fail_idx = -1 for i in range(nref): rv = mp_lib.mpf(ref[i]) cv = final[i][0] d = abs(rv - cv) # LMFDB strings have ~25-30 digits; compare to that precision if d > max_diff: max_diff = d if d > mp_lib.mpf("1e-20"): print(f"[main] mismatch at {i}: ref={ref[i][:30]} got={final[i][1][:30]} diff={d}", flush=True) if fail_idx < 0: fail_idx = i print(f"[main] max diff vs LMFDB (first {nref}): {max_diff}", flush=True) print(f"[main] first mismatch idx: {fail_idx}", flush=True) # Save arr = np.array([s for (_, s) in final], dtype="<U81") out = "lchi5_zeros_N5000_dps80.npy" np.save(out, arr) print(f"[main] saved {out} shape={arr.shape} dtype={arr.dtype}", flush=True) print(f"[main] first 3: {arr[:3]}", flush=True) print(f"[main] last: {arr[-1]}", flush=True) if __name__ == "__main__": main()
