#!/usr/bin/env python3
r"""E79.46 - low-complexity local transport autopsy for the zeta packet sequence.

Use the already-audited local supports from E79.44 and test whether they can be
generated by a single fixed local transport rule of the form

    T(S) = clip( (S + shift) U A ) \ R

with small, fixed add/remove sets A,R inside the 4-shell terminal window.
"""

from __future__ import annotations

import itertools
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent

WINDOW = 4
UNIVERSE = tuple(range(WINDOW))
SEQUENCE = [
    [1, 2, 3],   # N=8
    [0, 1, 2, 3],# N=10
    [0],         # N=12
    [1, 2, 3],   # N=14
    [1, 3],      # N=16
]
NS = [8, 10, 12, 14, 16]


def normalize(items):
    return sorted(set(i for i in items if 0 <= i < WINDOW))


def apply_rule(support, shift, add_set, remove_set):
    shifted = [j + shift for j in support]
    merged = set(normalize(shifted)) | set(add_set)
    result = sorted(j for j in merged if j not in remove_set)
    return result


def set_distance(a, b):
    return len(set(a).symmetric_difference(set(b)))


def all_small_sets(max_size):
    out = [[]]
    for k in range(1, max_size + 1):
        out.extend([list(c) for c in itertools.combinations(UNIVERSE, k)])
    return out


def main():
    add_sets = all_small_sets(2)
    remove_sets = all_small_sets(2)
    rows = []
    best = None
    perfect = []

    for shift in (-1, 0, 1):
        for add_set in add_sets:
            for remove_set in remove_sets:
                preds = []
                distances = []
                hits = 0
                for src, tgt in zip(SEQUENCE[:-1], SEQUENCE[1:]):
                    pred = apply_rule(src, shift, add_set, remove_set)
                    preds.append(pred)
                    dist = set_distance(pred, tgt)
                    distances.append(dist)
                    if dist == 0:
                        hits += 1
                score = (sum(distances), -hits, len(add_set) + len(remove_set))
                row = {
                    "shift": shift,
                    "add": add_set,
                    "remove": remove_set,
                    "predictions": preds,
                    "distances": distances,
                    "total_distance": sum(distances),
                    "exact_hits": hits,
                    "complexity": len(add_set) + len(remove_set),
                }
                rows.append(row)
                if all(d == 0 for d in distances):
                    perfect.append(row)
                if best is None or score < best[0]:
                    best = (score, row)

    out = {
        "statement": "E79.46 local transport autopsy",
        "window": WINDOW,
        "supports_local": [{"N": n, "support": s} for n, s in zip(NS, SEQUENCE)],
        "perfect_rules": perfect,
        "best_rule": best[1],
    }
    out_path = HERE / "E79_46_local_transport_autopsy_results.json"
    out_path.write_text(json.dumps(out, indent=2) + "\n", encoding="ascii")

    b = best[1]
    print(
        "best",
        "shift", b["shift"],
        "add", b["add"],
        "remove", b["remove"],
        "hits", b["exact_hits"],
        "distance", b["total_distance"],
    )
    print(f"WROTE {out_path.name}")


if __name__ == "__main__":
    main()
