#!/usr/bin/env python3
"""Generate L(s, chi_4 mod 5) zeros at N=5000, dps=80 via non-uniform partition + multiprocessing."""
import os, sys, time, math, json
import numpy as np
import multiprocessing as mp WORKDIR = "/workspace/03610627-b381-4cb3-9393-d1a3a0d57d46"
sys.path.insert(0, WORKDIR) from lchi5_cypari_worker import worker as base_worker DPS = 80
N_TARGET = 5000
TMAX = 4500.0
N_SEG = 80
N_WORKERS = 8 def cost_rate(t): return min(0.5, max(0.0005, 0.00013*t)) def build_partition(tmax=TMAX, nseg=N_SEG): ts = np.linspace(0, tmax, 10000) cs = np.array([cost_rate(t) for t in ts]) total = float(np.trapezoid(cs, ts)) target = total / nseg edges = [0.0] acc = 0.0 for i in range(1, len(ts)): acc += 0.5*(cs[i-1]+cs[i])*(ts[i]-ts[i-1]) if acc >= target: edges.append(float(ts[i])) acc = 0.0 if edges[-1] < tmax: edges.append(tmax) edges = sorted(set([round(e,3) for e in edges])) return edges def main(): edges = build_partition() intervals = [(edges[i], edges[i+1], DPS, i) for i in range(len(edges)-1)] print(f"[{time.strftime('%H:%M:%S')}] Built {len(intervals)} intervals over [0,{TMAX}]", flush=True) print(f" first widths: {[round(intervals[i][1]-intervals[i][0],2) for i in range(3)]}", flush=True) print(f" last widths : {[round(intervals[-1-i][1]-intervals[-1-i][0],2) for i in range(3)]}", flush=True) t_start = time.time() ctx = mp.get_context("spawn") results = {} with ctx.Pool(N_WORKERS) as pool: for ridx, tmin, tmax, elapsed, zs in pool.imap_unordered(base_worker, intervals): results[ridx] = (tmin, tmax, elapsed, zs) done = len(results) total_z = sum(len(v[3]) for v in results.values()) print(f"[{time.strftime('%H:%M:%S')}] seg {ridx:3d} [{tmin:7.2f},{tmax:7.2f}] nz={len(zs):4d} t={elapsed:6.1f}s | done {done}/{len(intervals)} totalZ={total_z}", flush=True) total_time = time.time() - t_start print(f"All workers finished in {total_time:.1f}s", flush=True) # Merge in order all_zeros = [] for idx in sorted(results.keys()): tmin, tmax, el, zs = results[idx] all_zeros.extend(zs) print(f"Total raw zeros collected: {len(all_zeros)}", flush=True) # Sort by float value, de-duplicate (within 1e-9), truncate to N_TARGET pairs = sorted(((float(s.replace(' ', '')), s) for s in all_zeros), key=lambda x: x[0]) dedup = [] for fv, s in pairs: if dedup and abs(fv - dedup[-1][0]) < 1e-9: continue dedup.append((fv, s)) print(f"After dedup: {len(dedup)} zeros", flush=True) if len(dedup) < N_TARGET: print(f"ERROR: only {len(dedup)} zeros, need {N_TARGET}", flush=True) sys.exit(2) final = [s for fv, s in dedup[:N_TARGET]] arr = np.array(final, dtype='<U81') out_path = os.path.join(WORKDIR, "lchi5_zeros_N5000_dps80.npy") np.save(out_path, arr) print(f"Saved {out_path} shape={arr.shape} dtype={arr.dtype}", flush=True) # Validation vs LMFDB with open(os.path.join(WORKDIR, "lmfdb_Lchi5.json")) as f: txt = f.read() lmfdb = json.loads(txt[txt.index('{'):])["positive_zeros"] print(f"Validating against {len(lmfdb)} LMFDB zeros...", flush=True) max_err = 0.0 for i, ref in enumerate(lmfdb): ours = final[i] # compare common prefix precision -- LMFDB has ~28 digits, ours ~65 diff = abs(float(ours) - float(ref)) if diff > max_err: max_err = diff if i < 5 or diff > 1e-15: print(f" [{i}] ref={ref[:30]} ours={ours[:30]} |diff|={diff:.2e}", flush=True) print(f"Max |diff| over first {len(lmfdb)} LMFDB zeros: {max_err:.3e}", flush=True) if __name__ == "__main__": main()
