#!/usr/bin/env python3
"""Verifier: what principal-invariance of I_partial does and does not hold."""
import itertools, math, numpy as np
FAIL=[]
def check(n, ok, extra=""):
    print(f"[{'ok ' if ok else 'FAIL'}] {n} {extra}");  FAIL.append(n) if not ok else None

# ---- A. theta(gamma) = id for gamma in the unit subgroup -------------------
# finite model: G abelian idele-class model, H <= G the S-unit subgroup,
# H_space = L^2(H\G),  (theta(u) xi)(a) = xi(u^-1 a).
def theta_matrix(G_ord, H_idx, u):
    """G = Z/G_ord written additively; H = subgroup generated by H_idx."""
    H = set()
    x = 0
    while x not in H:
        H.add(x); x = (x + H_idx) % G_ord
    cos = {}                      # coset representative for each element
    for g in range(G_ord):
        cos[g] = min((g + h) % G_ord for h in H)
    reps = sorted(set(cos.values()))
    idx = {r: i for i, r in enumerate(reps)}
    M = np.zeros((len(reps), len(reps)))
    for r in reps:                # (theta(u) xi)(a) = xi(a - u)
        M[idx[r], idx[cos[(r - u) % G_ord]]] = 1.0
    return M, reps, H

allok = True
for G_ord, H_idx in [(12,4),(12,3),(20,5),(30,6),(36,9)]:
    M0, reps, H = theta_matrix(G_ord, H_idx, 0)
    I = np.eye(len(reps))
    for gamma in H:
        M, _, _ = theta_matrix(G_ord, H_idx, gamma)
        if not np.allclose(M, I): allok = False
    # and a non-unit must act nontrivially somewhere
    nontriv = any(not np.allclose(theta_matrix(G_ord,H_idx,u)[0], I)
                  for u in range(G_ord) if u not in H)
    if not nontriv: allok = False
check("A. theta(gamma)=id for every unit gamma; non-units act nontrivially", allok)

# ---- B. affine invariance of the recovered f ------------------------------
# u_f(r) = int_A^{min(r,B)} f(lam)(r-lam) dlam/lam ;  u_f''(r) = f(r)/r
A_, B_ = 1.0, 4.0
def _simpson(g, a, b, n=20000):
    if b <= a: return 0.0
    n = n + (n % 2)
    h = (b-a)/n
    s = g(a) + g(b)
    for i in range(1, n):
        s += (4 if i % 2 else 2) * g(a + i*h)
    return s*h/3
def u_f(f, r):
    hi = min(r, B_)
    if hi <= A_: return 0.0
    return r*_simpson(lambda l: f(l)/l, A_, hi) - _simpson(f, A_, hi)
def second_deriv(g, r, h=1e-3):
    return (g(r+h) - 2*g(r) + g(r-h))/h**2

f = lambda lam: math.sin(3*lam) + 1.7
rs = [1.5, 2.0, 2.5, 3.0, 3.5]
base = [second_deriv(lambda r: u_f(f, r), r) for r in rs]
truth = [f(r)/r for r in rs]
check("B1. u_f'' = f(r)/r recovers f", 
      all(abs(b-t) < 5e-3 for b, t in zip(base, truth)),
      f"max err {max(abs(b-t) for b,t in zip(base,truth)):.2e}")
allok = True
for (al, be) in [(2.3,-1.1),(-0.7,4.2),(10.0,10.0)]:
    pert = [second_deriv(lambda r: u_f(f, r) + al*r + be, r) for r in rs]
    if not all(abs(p-b) < 1e-6 for p, b in zip(pert, base)): allok = False
check("B2. adding an affine function changes nothing (local principal invariance)", allok)

# ---- C. the local principal subspace is ZERO ------------------------------
# f -> D_f is injective, so no nonzero f is locally principal.
# Test: distinct f give distinct angular densities.
fs = [lambda l: math.sin(3*l)+1.7, lambda l: math.cos(2*l)+2.0,
      lambda l: 1.0, lambda l: l**2/8]
dens = [[second_deriv(lambda r, g=g: u_f(g, r), r) for r in rs] for g in fs]
sep = all(max(abs(np.array(dens[i])-np.array(dens[j]))) > 1e-2
          for i, j in itertools.combinations(range(len(fs)), 2))
check("C. f |-> D_f injective: local principal subspace is {0}", sep)

print()
print("VERDICT:", "ALL CHECKS PASS" if not FAIL else f"FAILED: {FAIL}")
