#!/usr/bin/env python3
"""Exact finite checks for the H7 selective-coordinate criterion."""

from itertools import combinations, product


def add(x, y, p):
    return tuple((a + b) % p for a, b in zip(x, y))


def multiply(x, y, p):
    return tuple(a * b % p for a, b in zip(x, y))


def all_ideals(p, m):
    ring = tuple(product(range(p), repeat=m))
    ideals = []
    for mask in range(1 << len(ring)):
        subset = {ring[i] for i in range(len(ring)) if mask >> i & 1}
        if (0,) * m not in subset:
            continue
        if not all(add(x, y, p) in subset for x in subset for y in subset):
            continue
        if not all(multiply(a, x, p) in subset for a in ring for x in subset):
            continue
        ideals.append(subset)
    return ring, ideals


def balanced_code(r, q):
    return tuple(c for c in product(range(-q, q + 1), repeat=r)
                 if sum(abs(value) for value in c) <= q)


def moment_vector(c, q, p):
    q_inverse = pow(q, -1, p)
    result = []
    for exponent in range(1, 4 * len(c), 2):
        value = sum(
            3**j * (1 if entry > 0 else -1 if entry < 0 else 0)
            * pow(abs(entry) * q_inverse % p, exponent, p)
            for j, entry in enumerate(c)
        )
        result.append(value % p)
    return tuple(result)


def information_bound(cardinality, p):
    k = 0
    capacity = 1
    while capacity < cardinality:
        capacity *= p
        k += 1
    return k


def minimum_separating_coordinates(r, q, p):
    code = balanced_code(r, q)
    images = tuple(moment_vector(c, q, p) for c in code)
    m = 2 * r
    for k in range(m + 1):
        good = []
        for indices in combinations(range(m), k):
            projected = {
                tuple(image[index] for index in indices) for image in images
            }
            if len(projected) == len(code):
                good.append(indices)
        if good:
            return len(code), k, tuple(good)
    raise AssertionError("the full moment embedding must separate")


print("A. Ideals of small products are coordinate ideals")
for p, m in ((3, 2), (2, 3)):
    ring, ideals = all_ideals(p, m)
    coordinate_ideals = []
    for chosen_count in range(m + 1):
        for chosen in combinations(range(m), chosen_count):
            chosen = set(chosen)
            coordinate_ideals.append({
                x for x in ring
                if all(x[i] == 0 for i in range(m) if i not in chosen)
            })
    assert {frozenset(ideal) for ideal in ideals} == {
        frozenset(ideal) for ideal in coordinate_ideals
    }
print("  every enumerated ideal is generated by primitive idempotents")

print("\nB. Exact minimum separating-coordinate counts")
examples = (
    (1, 4, 17),
    (2, 4, 317),
    (2, 12, 317),
    (3, 12, 26783297),
    (3, 30, 26783297),
)
records = []
for r, q, p in examples:
    cardinality, kappa, good = minimum_separating_coordinates(r, q, p)
    lower = information_bound(cardinality, p)
    assert lower <= kappa <= 2 * r
    records.append((r, q, p, cardinality, lower, kappa, good[0]))
assert any(lower == kappa for _, _, _, _, lower, kappa, _ in records)
assert any(lower < kappa for _, _, _, _, lower, kappa, _ in records)
print("  kappa sometimes attains and sometimes exceeds information capacity")

print("\nC. Hitting-set formulation agrees with projected injectivity")
r, q, p = 2, 12, 317
code = balanced_code(r, q)
images = {c: moment_vector(c, q, p) for c in code}
_, kappa, good = minimum_separating_coordinates(r, q, p)
chosen = set(good[0])
for left_index, left in enumerate(code):
    for right in code[left_index + 1:]:
        difference_support = {
            j for j, (a, b) in enumerate(zip(images[left], images[right]))
            if a != b
        }
        assert chosen & difference_support
for smaller in combinations(range(2 * r), kappa - 1):
    smaller = set(smaller)
    assert any(
        not (smaller & {
            j for j, (a, b) in enumerate(zip(images[left], images[right]))
            if a != b
        })
        for left_index, left in enumerate(code)
        for right in code[left_index + 1:]
    )
print("  exact hitting and injectivity criteria coincide")

print("\nD. Bounded block saturation survives coordinate projection")
p = 17
full_block = tuple(product(range(p), repeat=2))
for selected_count in (1, 2):
    for selected in combinations(range(2), selected_count):
        projected = {tuple(y[i] for i in selected) for y in full_block}
        assert len(projected) == p**selected_count
print("  every selected quotient has exact cardinality p^|S|")

print("\nVERDICT: H7 SELECTIVE-MOMENT QUOTIENT CRITERION CHECKS PASS")
