#!/usr/bin/env python3
import math
import sys

import numpy as np
from numpy.linalg import inv, norm

sys.path.append("/Users/dt/riemann/riemann-program/03-research/phase-71-cand1-convergence")
sys.path.append("/Users/dt/riemann/riemann-program/03-research/phase-72-feshbach-leakage-calculus")
sys.path.append("/Users/dt/riemann/riemann-program/03-research/phase-73-cauchy-projection")

from E71_9_relative_arch_background_probe import build  # noqa: E402
from E72_396_cauchy_projection_probe import GAMMAS  # noqa: E402
from E73_223_coefficient_ball_budget import cauchy_rows, projector  # noqa: E402


def setup(lam, n_modes):
    H, idx, L = build(lam, n_modes, include_arith=True)
    vals, vecs = np.linalg.eigh(H)
    mu = vals[0]
    xi = vecs[:, 0]
    if xi[len(xi) // 2] < 0:
        xi = -xi
    xi = xi / norm(xi)
    d = 2.0 * np.pi * idx / L
    return H.astype(complex), idx.astype(int), d, L, float(mu), xi.astype(complex)


def bexp(z, L):
    return math.log(max(float(abs(complex(z))), 1e-300)) / math.log(L)


def primitive_columns(Q, d, degree):
    cols = []
    labels = []
    for j in range(Q.shape[0]):
        base = Q[j].conj()
        for k in range(degree + 1):
            cols.append((d**k) * base)
            labels.append((j, k))
    return np.column_stack(cols), labels


def fit_left_coborder(rho, E, prim):
    # Rows generated by Y^*E with Y in span(prim columns).
    rows = (prim.conj().T @ E)
    # Find coefficients a such that a @ rows approximates rho.
    sol, *_ = np.linalg.lstsq(rows.T, rho.T, rcond=None)
    approx = sol @ rows
    return approx


def forbidden_full_rowspace(rho, E):
    # Calibration only: arbitrary rowspace projection.
    sol, *_ = np.linalg.lstsq(E.T, rho.T, rcond=None)
    return sol @ E


def run():
    print("E73.242 structured left-coborder audit")
    print("Fits rho=qH(I-P) by Y*E with Y in span{D^k q_j*}; compares forbidden full rowspace.")
    print(" lam      L gamma row deg centerB resPairB resNormB fullPairB fullNormB")
    for lam, n_modes in [(8, 6), (10, 8), (12, 10), (16, 20)]:
        H, idx, d, L, mu, xi = setup(lam, n_modes)
        I = np.eye(len(idx), dtype=complex)
        E = H - mu * I
        for gamma in GAMMAS[:2]:
            Q = cauchy_rows(-1j * gamma, d)
            P = projector(Q)
            R = I - P
            for row_id in range(2):
                rho = Q[row_id] @ H @ R
                center = rho @ xi
                full = forbidden_full_rowspace(rho, E)
                full_res = rho - full
                for deg in [0, 1, 2, 3, 4]:
                    prim, _labels = primitive_columns(Q, d, deg)
                    approx = fit_left_coborder(rho, E, prim)
                    res = rho - approx
                    print(
                        f"{lam:4d} {L:8.3f} {gamma:6.2f} {row_id:3d}"
                        f" {deg:3d} {bexp(center, L):8.2f}"
                        f" {bexp(res @ xi, L):8.2f} {bexp(norm(res), L):8.2f}"
                        f" {bexp(full_res @ xi, L):9.2f} {bexp(norm(full_res), L):9.2f}"
                    )


if __name__ == "__main__":
    run()
