"""
Localized Weil Detector: Q = M_zeros - M_arith
Implementation per -v8-validated-data.md. The quadratic form Q on the J-dim Hermite-Gauss basis φ_k(t) = (1/√σ) h_k((t-T0)/σ), k = 0..J-1
is built as Q = M_zeros - M_arith from the Weil explicit formula. Sign convention validated numerically against the formula: Σ_γ h(γ) = [2 h(i/2) - g_B(0) log π] + (1/2π) ∫ h(r) Re ψ(1/4+ir/2) dr - 2 Σ_{n≥1} Λ(n)/√n g_B(log n)
with g_B(u) = (1/2π) ∫ h(r) e^{-iur} dr (Bombieri convention). For our internal helper g_mine(u) = ∫ h(r) e^{-iur} dr = 2π g_B(u), so: Σ_γ h(γ) = polar + arch - prime_full
where prime_full = (1/π) Σ Λ(n)/√n Re g_mine(log n). Hence: M_arith = M_polar + M_arch - M_primes Q = M_zeros - M_arith
"""
import numpy as np
from numpy.polynomial.hermite import hermgauss
from scipy.special import digamma, gammaln
from sympy import primerange def _phi_at_points(t_points, sigma, T0, J): """Evaluate φ_k(t) = (1/√σ) h_k((t-T0)/σ) at given t. Returns (N, J).""" t = np.asarray(t_points, dtype=np.float64) u = (t - T0) / sigma N = len(t) h = np.zeros((J, N)) h[0] = np.pi ** (-0.25) * np.exp(-u * u / 2) if J > 1: h[1] = np.sqrt(2.0) * u * h[0] for n in range(1, J - 1): h[n + 1] = np.sqrt(2.0 / (n + 1)) * u * h[n] - np.sqrt(n / (n + 1)) * h[n - 1] return (h / np.sqrt(sigma)).T def _g_at_u(u_array, sigma, T0, J, n_nodes=200): """ Compute g_ij(u) = ∫ φ_i(r) φ_j(r) e^{-i u r} dr for an array of u. Returns shape (len(u), J, J), complex. """ u_array = np.asarray(u_array, dtype=np.float64) x, w = hermgauss(n_nodes) H = np.zeros((J, n_nodes)) H[0] = 1.0 if J > 1: H[1] = 2 * x for n in range(1, J - 1): H[n + 1] = 2 * x * H[n] - 2 * n * H[n - 1] norm = np.array([0.5 * (k * np.log(2) + gammaln(k + 1)) for k in range(J)]) norm_ij = norm[:, None] + norm[None, :] + 0.5 * np.log(np.pi) exp_neg_norm = np.exp(-norm_ij) omega = sigma * u_array # (M,) phase = np.exp(-1j * omega[:, None] * x[None, :]) # (M, n_nodes) G_un = np.einsum("ik,mk,jk->mij", H, w * phase, H) # (M, J, J) G = G_un * exp_neg_norm phase_T0 = np.exp(-1j * u_array * T0) return G * phase_T0[:, None, None] def compute_Q( zeros, T0, sigma, J, primes_cutoff=100_000, n_nodes_quad=200, include_negative_zeros=True,
): """ Construct the localized Weil quadratic form Q = M_zeros - M_arith. Parameters ---------- zeros : array_like Imaginary parts γ of nontrivial zeros (positive). Both ±γ are summed (set include_negative_zeros=False to disable). T0 : float Center of the Hermite-Gauss basis (frequency / γ axis). sigma : float Width of the basis. J : int Basis dimension. primes_cutoff : int, optional Mandatory cutoff X for prime-power sum (default 1e5 per spec). n_nodes_quad : int, optional Gauss-Hermite quadrature nodes (200 is sufficient for J≤10). Returns ------- Q : (J, J) ndarray Q = M_zeros - M_arith. Symmetric real. components : dict Sub-matrices "M_zeros", "M_primes", "M_arch", "M_polar". """ # ---- M_zeros ---- zeros = np.asarray(zeros, dtype=np.float64) if include_negative_zeros: g_all = np.concatenate([zeros, -zeros]) else: g_all = zeros phi = _phi_at_points(g_all, sigma, T0, J) # (N, J) M_zeros = phi.T @ phi # real, symmetric # ---- M_primes ---- primes_list = list(primerange(2, primes_cutoff + 1)) u_vals, weights = [], [] for p in primes_list: k = 1 pk = p while pk <= primes_cutoff: u_vals.append(k * np.log(p)) weights.append(np.log(p) / np.sqrt(pk)) k += 1 pk *= p u_vals = np.array(u_vals) weights = np.array(weights) M_primes = np.zeros((J, J)) chunk = 2000 for i in range(0, len(u_vals), chunk): u_chunk = u_vals[i : i + chunk] w_chunk = weights[i : i + chunk] g_chunk = _g_at_u(u_chunk, sigma, T0, J, n_nodes_quad) M_primes += np.sum(w_chunk[:, None, None] * np.real(g_chunk), axis=0) / np.pi # ---- M_arch ---- x, w = hermgauss(n_nodes_quad) H = np.zeros((J, n_nodes_quad)) H[0] = 1.0 if J > 1: H[1] = 2 * x for n in range(1, J - 1): H[n + 1] = 2 * x * H[n] - 2 * n * H[n - 1] norm = np.array([0.5 * (k * np.log(2) + gammaln(k + 1)) for k in range(J)]) norm_ij = norm[:, None] + norm[None, :] + 0.5 * np.log(np.pi) exp_neg_norm = np.exp(-norm_ij) t_nodes = T0 + sigma * x psi_vals = np.real(digamma(0.25 + 0.5j * t_nodes)) diag = w * psi_vals HP = H * diag[None, :] M_arch = (HP @ H.T) * exp_neg_norm / (2 * np.pi) # ---- M_polar ---- # 2 h(i/2) is exp suppressed by exp(-T0²/2σ²); neglect for T0/σ >~ 5. M_polar = -(np.log(np.pi) / (2 * np.pi)) * np.eye(J) M_arith = M_polar + M_arch - M_primes Q = M_zeros - M_arith Q = 0.5 * (Q + Q.T) # enforce symmetry against floating roundoff components = { "M_zeros": M_zeros, "M_primes": M_primes, "M_arch": M_arch, "M_polar": M_polar, "M_arith": M_arith, } return Q, components
