#!/usr/bin/env python3
"""
Multiplicative Resonance Program - Data Generation Script This script reproduces the computational dataset described in:
"The Multiplicative Resonance Program: Detecting and Ruling Out Coherent Amplification in Arithmetic L-Functions" (research-program-v3.pdf) Dataset specification:
- Functions: ζ, L(s,χ₄), f_rand, L_DH, L_DH^(ε)
- Truncation lengths N: 10^4, 10^5, 10^6
- Height range T: [80, 92] (covering known zero at t ≈ 85.7)
- Numerical precision: float64 with Kahan compensated summation
- Target relative error: < 10^-12 Author: Generated for Multiplicative Resonance Program
Date: 2024
""" import numpy as np
import pandas as pd
import os
from pathlib import Path # ============================================================================
# CORE NUMERICAL ENGINE (Section 12.1 of research program)
# ============================================================================ def kahan_sum(values): """ Kahan compensated summation for complex arrays. Reduces round-off error from O(ε·N) to O(ε·log N) """ total = 0.0 + 0.0j c = 0.0 + 0.0j for val in values: y = val - c t = total + y c = (t - total) - y total = t return total def compute_partial_sum_D(t_val, N, coeffs): """ Compute D_F(t; N) = Σ_{n≤N} a_n(F) / n^(1/2 + it) Using Kahan compensated summation for numerical stability. """ n_values = np.arange(1, N + 1) n_power = 1.0 / np.sqrt(n_values) phase = -1j * t_val * np.log(n_values) exp_phase = np.exp(phase) terms = coeffs[1:N+1] * n_power * exp_phase result = kahan_sum(terms) return result # ============================================================================
# COEFFICIENT GENERATORS (Section 3 of research program)
# ============================================================================ def compute_dirichlet_coefficients_zeta(max_n): """Riemann zeta: a_n = 1 for all n""" coeffs = np.ones(max_n + 1, dtype=np.complex128) coeffs[0] = 0 return coeffs def compute_dirichlet_coefficients_chi4(max_n): """L(s, χ_4) with χ_4 real character mod 5""" chi4_vals = {0: 0, 1: 1, 2: -1, 3: -1, 4: 1} coeffs = np.zeros(max_n + 1, dtype=np.complex128) for n in range(1, max_n + 1): coeffs[n] = chi4_vals[n % 5] return coeffs def compute_dirichlet_coefficients_random(max_n, seed=42): """Random multiplicative function""" np.random.seed(seed) coeffs = np.zeros(max_n + 1, dtype=np.complex128) coeffs[1] = 1.0 is_prime = np.ones(max_n + 1, dtype=bool) is_prime[0] = is_prime[1] = False for i in range(2, int(np.sqrt(max_n)) + 1): if is_prime[i]: is_prime[i*i::i] = False primes = np.where(is_prime)[0] prime_coeffs = {} for p in primes: prime_coeffs[p] = np.random.choice([-1.0, 1.0]) for n in range(1, max_n + 1): if n == 1: coeffs[n] = 1.0 elif n in prime_coeffs: coeffs[n] = prime_coeffs[n] else: n_temp = n coeff = 1.0 for p in primes: if p > n_temp: break if n_temp % p == 0: power = 0 while n_temp % p == 0: power += 1 n_temp //= p coeff *= prime_coeffs[p] ** power coeffs[n] = coeff return coeffs def compute_dirichlet_coefficients_DH(max_n, kappa=None): """Davenport-Heilbronn function (Section 3.1)""" if kappa is None: sqrt5 = np.sqrt(5) kappa = (sqrt5 - 1) / (2 * np.sqrt(sqrt5 * (sqrt5 - 1))) chi_vals = {1: 1+0j, 2: 0+1j, 3: 0-1j, 4: -1+0j, 0: 0+0j} coeffs = np.zeros(max_n + 1, dtype=np.complex128) for n_val in range(1, max_n + 1): n_mod5 = n_val % 5 chi_n = chi_vals[n_mod5] chi_bar_n = np.conj(chi_n) coeffs[n_val] = ((1 - 1j*kappa)/2) * chi_n + ((1 + 1j*kappa)/2) * chi_bar_n return coeffs, kappa # ============================================================================
# MAIN DATASET GENERATION
# ============================================================================ def generate_dataset(N_values=[10**4, 10**5, 10**6], T_min=80, T_max=92, output_dir='downloads'): """ Generate the complete Multiplicative Resonance Program dataset. """ os.makedirs(f'{output_dir}/raw', exist_ok=True) os.makedirs(f'{output_dir}/processed', exist_ok=True) print(f"Generating dataset for N = {N_values}") print(f"T range: [{T_min}, {T_max}]") for N in N_values: print(f"\nComputing N = {N:,}...") # Generate t grid delta_t = 2 * np.pi / np.log(N) t_grid = np.arange(T_min, T_max, delta_t) # Generate coefficients coeffs_dict = { 'zeta': compute_dirichlet_coefficients_zeta(N), 'L_chi4': compute_dirichlet_coefficients_chi4(N), 'f_rand': compute_dirichlet_coefficients_random(N, seed=42), } coeffs_DH, kappa = compute_dirichlet_coefficients_DH(N) coeffs_dict['L_DH'] = coeffs_DH coeffs_DH_pert, kappa_pert = compute_dirichlet_coefficients_DH(N, kappa=kappa+0.01) coeffs_dict['L_DH_perturbed'] = coeffs_DH_pert # Compute time series for func_name, coeffs in coeffs_dict.items(): print(f" Computing {func_name}...") results = [] for t_val in t_grid: D = compute_partial_sum_D(t_val, N, coeffs) results.append({ 't': t_val, 'D_real': D.real, 'D_imag': D.imag, 'D_magnitude': abs(D), 'D_phase': np.angle(D) }) df = pd.DataFrame(results) filename = f'{output_dir}/raw/time_series_{func_name}_N{N}.parquet' df.to_parquet(filename, index=False) print(f" Saved: {filename}") print("\nDataset generation complete!") if __name__ == "__main__": generate_dataset()
